robot_control_topic: /RosAria/cmd_vel
robot_control_message: Twist

max_obstacle_distance: 0.55
density_gain: 0.3
min_observation_radius: 0.4
observation_radius_gain: 0.0
min_threshold: 0.23
cumulative_distance: 0.15

obstacle_avoidance:
  n: 2.0
  a: 4.0
  b: 4.0
  k: 0.00001