robot_type: 'Pioneer'
control_frequency: 30

gains:
  linear: 0.2
  angular: 0.2

a: 0.15

robot_control_topic: '/RosAria/cmd_vel'
robot_control_message: 'Twist'

angular_velocity_priority_gain: 1.0
distance_to_change_path_index: 0.25
min_velocity: 0.1
max_linear_velocity: 0.4
world_frame: 'map'
robot_frame: 'base_link'
path_topic: '/local_path'