robot_type: 'Pioneer'
control_frequency: 30

gains:
  linear: 0.1
  angular: 0.1

a: 0.15

robot_control_topic: '/RosAria/cmd_vel'
robot_control_message: 'Twist'

angular_velocity_priority_gain: 2.0
distance_to_change_path_index: 0.25
min_velocity: 0.1
max_linear_velocity: 0.1
world_frame: 'world'
robot_frame: 'P1'
path_topic: '/local_path'