robot_type: 'Pioneer'
control_frequency: 30

gains:
  linear: 5
  angular: 2

a: 0.15

robot_control_topic: '/cmd_vel'
robot_control_message: 'Twist'

angular_velocity_priority_gain: 1.0
distance_to_change_path_index: 0.25
min_velocity: 0.35
max_linear_velocity: 0.3
max_angular_velocity: 1.0
world_frame: 'map'
robot_frame: 'base_link'
path_topic: '/local_path'